baseurl      = "https://marlisschneider.github.io/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"
relativeURLs = true

[module]
  [[module.mounts]]
    source = "./node_modules/commentbox.io/dist"
    target = "static/js/commentbox.io"

[[module.mounts]]
source = "static"
target = "static"

[params]
  contentTypeName = "blog"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"
  mainSections = ["blog"]
  commentboxProjectId = "5700625182490624-proj"

  additionalCSS = ["/w3.css", "/custom.css"]

  # Subtitle for home
  homeSubtitle = "I am an economics PhD student at NHH Norwegian School of Economics in Bergen, Norway."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  [params.portrait]
      path = "portrait.jpeg"
      alt = "Portrait"

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "email"
    url = "mailto:marlis.schneider@nhh.no"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/MarMaSchneider"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hi, I am Marlis! 👋"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "marlis.schneider"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    name      = "Resources"
    url       = "/resources"
    weight    = "3"
  [[menu.main]]
    name      = "About"
    url       = "/about"
    weight    = "1"
  [[menu.main]]
    name     = "Blog"
    url      = "/blog"
    weight   = "4"
  [[menu.main]]
    name     = "Research"
    url      = "/research"
    weight   = "2"
